var text = require('GetText');

module.exports = {
    get countryData() {return countryData},

    getCountryGroupFromCountryCode(country) {
        return countryData[_.find(Object.keys(countryData), groupKey => countryData[groupKey][country])];
    },

    getCountryName(countryValue) {
        return getCountriesFromCountryData()[countryValue];
    },

    isCountryMilitaryOrTerritory(countryValue) {
        switch ( this.getCountryGroupFromCountryCode( countryValue ) ) {
            case this.countryData.US_TERRITORY:
                return true;
            case this.countryData.MILITARY:
                return true;
            default:
                return false;
        }
    },

    isCountryUsesProvince( countryValue ) {
        return countryValue === 'CA';
    },

    getDisplayNameFromCountryValue( countryValue ) {
        var countryName = this.getCountryName( countryValue );
        switch ( this.getCountryGroupFromCountryCode( countryValue ) ) {
            case this.countryData.US_TERRITORY:
                return countryName;
            case this.countryData.MILITARY:
                return `${countryValue} - ${countryName}`;
        }
    },

    getUsTerritoryAndMilitaryCountries() {
        return _.extend({}, countryData.US_TERRITORY, countryData.MILITARY);
    },

    isNotInNorthAmerica(country) {
        return countryData.NORTH_AMERICA[country] === undefined;
    }
};

function getCountriesFromCountryData() {
    return _.reduce(countryData, (memo, data) => _.extend(memo, data), {});
}

var countryData = {
    NORTH_AMERICA: {
        US: text('country.US.name'),
        CA: text('country.CA.name')
    },
    US_TERRITORY: {
        AS: text('country.AS.name'),
        GU: text('country.GU.name'),
        MP: text('country.MP.name'),
        PR: text('country.PR.name'),
        VI: text('country.VI.name')
    },
    MILITARY: {
        AA: text('address.military.aa'),
        AEA: text('address.military.aea'),
        AP: text('address.military.ap')
    },
    INTERNATIONAL: {
        AL: text('country.AL.name'),
        DZ: text('country.DZ.name'),
        AD: text('country.AD.name'),
        AO: text('country.AO.name'),
        AI: text('country.AI.name'),
        AQ: text('country.AQ.name'),
        AG: text('country.AG.name'),
        AR: text('country.AR.name'),
        AM: text('country.AM.name'),
        AW: text('country.AW.name'),
        AT: text('country.AT.name'),
        AZ: text('country.AZ.name'),
        BS: text('country.BS.name'),
        BH: text('country.BH.name'),
        BD: text('country.BD.name'),
        BB: text('country.BB.name'),
        BY: text('country.BY.name'),
        BE: text('country.BE.name'),
        BZ: text('country.BZ.name'),
        BJ: text('country.BJ.name'),
        BM: text('country.BM.name'),
        BT: text('country.BT.name'),
        BO: text('country.BO.name'),
        BA: text('country.BA.name'),
        BW: text('country.BW.name'),
        BV: text('country.BV.name'),
        BR: text('country.BR.name'),
        IO: text('country.IO.name'),
        BN: text('country.BN.name'),
        BG: text('country.BG.name'),
        BF: text('country.BF.name'),
        BI: text('country.BI.name'),
        KH: text('country.KH.name'),
        CM: text('country.CM.name'),
        CV: text('country.CV.name'),
        KY: text('country.KY.name'),
        CF: text('country.CF.name'),
        TD: text('country.TD.name'),
        CL: text('country.CL.name'),
        CN: text('country.CN.name'),
        CX: text('country.CX.name'),
        CC: text('country.CC.name'),
        CO: text('country.CO.name'),
        KM: text('country.KM.name'),
        CG: text('country.CG.name'),
        CD: text('country.CD.name'),
        CK: text('country.CK.name'),
        CR: text('country.CR.name'),
        CI: text('country.CI.name'),
        HR: text('country.HR.name'),
        CU: text('country.CU.name'),
        CY: text('country.CY.name'),
        CZ: text('country.CZ.name'),
        DK: text('country.DK.name'),
        DJ: text('country.DJ.name'),
        DM: text('country.DM.name'),
        DO: text('country.DO.name'),
        EC: text('country.EC.name'),
        EG: text('country.EG.name'),
        SV: text('country.SV.name'),
        GQ: text('country.GQ.name'),
        ER: text('country.ER.name'),
        EE: text('country.EE.name'),
        ET: text('country.ET.name'),
        FK: text('country.FK.name'),
        FO: text('country.FO.name'),
        FJ: text('country.FJ.name'),
        FI: text('country.FI.name'),
        FR: text('country.FR.name'),
        GF: text('country.GF.name'),
        PF: text('country.PF.name'),
        TF: text('country.TF.name'),
        GA: text('country.GA.name'),
        GM: text('country.GM.name'),
        GE: text('country.GE.name'),
        DE: text('country.DE.name'),
        GH: text('country.GH.name'),
        GI: text('country.GI.name'),
        IQ: text('country.IQ.name'),
        GL: text('country.GL.name'),
        GR: text('country.GR.name'),
        GD: text('country.GD.name'),
        GP: text('country.GP.name'),
        GT: text('country.GT.name'),
        GG: text('country.GG.name'),
        GN: text('country.GN.name'),
        GW: text('country.GW.name'),
        GY: text('country.GY.name'),
        HN: text('country.HN.name'),
        VA: text('country.VA.name'),
        HM: text('country.HM.name'),
        HT: text('country.HT.name'),
        HU: text('country.HU.name'),
        HK: text('country.HK.name'),
        IS: text('country.IS.name'),
        IE: text('country.IE.name'),
        IR: text('country.IR.name'),
        ID: text('country.ID.name'),
        IN: text('country.IN.name'),
        IM: text('country.IM.name'),
        IL: text('country.IL.name'),
        IT: text('country.IT.name'),
        JM: text('country.JM.name'),
        JP: text('country.JP.name'),
        JE: text('country.JE.name'),
        JO: text('country.JO.name'),
        KZ: text('country.KZ.name'),
        KR: text('country.KR.name'),
        KP: text('country.KP.name'),
        KI: text('country.KI.name'),
        KE: text('country.KE.name'),
        KW: text('country.KW.name'),
        KG: text('country.KG.name'),
        LA: text('country.LA.name'),
        LV: text('country.LV.name'),
        LB: text('country.LB.name'),
        LS: text('country.LS.name'),
        LR: text('country.LR.name'),
        LY: text('country.LY.name'),
        LI: text('country.LI.name'),
        LU: text('country.LU.name'),
        LT: text('country.LT.name'),
        MG: text('country.MG.name'),
        MK: text('country.MK.name'),
        MO: text('country.MO.name'),
        MW: text('country.MW.name'),
        MV: text('country.MV.name'),
        MY: text('country.MY.name'),
        MH: text('country.MH.name'),
        MT: text('country.MT.name'),
        ML: text('country.ML.name'),
        MQ: text('country.MQ.name'),
        MU: text('country.MU.name'),
        MR: text('country.MR.name'),
        YT: text('country.YT.name'),
        MX: text('country.MX.name'),
        FM: text('country.FM.name'),
        MD: text('country.MD.name'),
        MS: text('country.MS.name'),
        MN: text('country.MN.name'),
        MC: text('country.MC.name'),
        MA: text('country.MA.name'),
        MZ: text('country.MZ.name'),
        MM: text('country.MM.name'),
        NL: text('country.NL.name'),
        NP: text('country.NP.name'),
        NR: text('country.NR.name'),
        NA: text('country.NA.name'),
        NZ: text('country.NZ.name'),
        NC: text('country.NC.name'),
        AN: text('country.AN.name'),
        NG: text('country.NG.name'),
        NE: text('country.NE.name'),
        NI: text('country.NI.name'),
        NF: text('country.NF.name'),
        NU: text('country.NU.name'),
        NO: text('country.NO.name'),
        PW: text('country.PW.name'),
        PK: text('country.PK.name'),
        OM: text('country.OM.name'),
        PE: text('country.PE.name'),
        PY: text('country.PY.name'),
        PG: text('country.PG.name'),
        PA: text('country.PA.name'),
        PS: text('country.PS.name'),
        PL: text('country.PL.name'),
        PN: text('country.PN.name'),
        PH: text('country.PH.name'),
        PT: text('country.PT.name'),
        QA: text('country.QA.name'),
        RE: text('country.RE.name'),
        RO: text('country.RO.name'),
        RU: text('country.RU.name'),
        RW: text('country.RW.name'),
        LC: text('country.LC.name'),
        KN: text('country.KN.name'),
        SH: text('country.SH.name'),
        SM: text('country.SM.name'),
        WS: text('country.WS.name'),
        VC: text('country.VC.name'),
        PM: text('country.PM.name'),
        CS: text('country.CS.name'),
        SN: text('country.SN.name'),
        SA: text('country.SA.name'),
        ST: text('country.ST.name'),
        SL: text('country.SL.name'),
        SC: text('country.SC.name'),
        SI: text('country.SI.name'),
        SK: text('country.SK.name'),
        SG: text('country.SG.name'),
        SB: text('country.SB.name'),
        SO: text('country.SO.name'),
        ZA: text('country.ZA.name'),
        GS: text('country.GS.name'),
        ES: text('country.ES.name'),
        LK: text('country.LK.name'),
        TP: text('country.TP.name'),
        SJ: text('country.SJ.name'),
        SD: text('country.SD.name'),
        SR: text('country.SR.name'),
        SZ: text('country.SZ.name'),
        SE: text('country.SE.name'),
        CH: text('country.CH.name'),
        SY: text('country.SY.name'),
        TW: text('country.TW.name'),
        TJ: text('country.TJ.name'),
        TZ: text('country.TZ.name'),
        TH: text('country.TH.name'),
        TL: text('country.TL.name'),
        TG: text('country.TG.name'),
        TK: text('country.TK.name'),
        TO: text('country.TO.name'),
        AF: text('country.AF.name'),
        TT: text('country.TT.name'),
        TN: text('country.TN.name'),
        TR: text('country.TR.name'),
        TM: text('country.TM.name'),
        TC: text('country.TC.name'),
        TV: text('country.TV.name'),
        UG: text('country.UG.name'),
        UA: text('country.UA.name'),
        AE: text('country.AE.name'),
        GB: text('country.GB.name'),
        UM: text('country.UM.name'),
        UY: text('country.UY.name'),
        UZ: text('country.UZ.name'),
        VU: text('country.VU.name'),
        VE: text('country.VE.name'),
        VN: text('country.VN.name'),
        VG: text('country.VG.name'),
        WF: text('country.WF.name'),
        EH: text('country.EH.name'),
        YE: text('country.YE.name'),
        YU: text('country.YU.name'),
        ZM: text('country.ZM.name'),
        ZW: text('country.ZW.name')
    }
};

